// apps/mvvm-angular/src/app/components/sensor-reading-card/sensor-reading-card.component.ts
import { Component, AfterViewInit, ElementRef, ViewChild } from '@angular/core';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import {
  sensorReadingViewModel,
  SensorReadingListData,
} from '@repo/view-models/SensorReadingViewModel';
import { Observable } from 'rxjs';
import { Chart } from 'chart.js/auto';

@Component({
  selector: 'app-sensor-reading-card',
  standalone: true,
  imports: [RouterModule, CommonModule],
  templateUrl: './sensor-reading-card.component.html',
  styleUrl: './sensor-reading-card.component.scss',
})
export class SensorReadingCardComponent implements AfterViewInit {
  public vm = sensorReadingViewModel;
  public data$: Observable<SensorReadingListData | null>;
  public loading$: Observable<boolean>;
  public error$: Observable<any>;

  @ViewChild('readingsChart') readingsChartRef?: ElementRef<HTMLCanvasElement>;
  private chartInstance?: Chart;

  constructor() {
    this.data$ = this.vm.data$;
    this.loading$ = this.vm.isLoading$;
    this.error$ = this.vm.error$;

    this.vm.fetchCommand.execute();
  }

  ngAfterViewInit(): void {
    this.data$.subscribe((data) => {
      if (data && data.length > 0 && this.readingsChartRef) {
        this.initChart(data);
      }
    });
  }

  private initChart(data: SensorReadingListData): void {
    if (!this.readingsChartRef) return;
    const canvas = this.readingsChartRef.nativeElement;
    const ctx = canvas.getContext('2d');

    if (!ctx) {
      console.error('Failed to get 2D context for chart');
      return;
    }

    if (this.chartInstance) {
      this.chartInstance.destroy(); // Destroy previous chart instance
    }

    this.chartInstance = new Chart(ctx, {
      type: 'line',
      data: {
        labels: data.map((r) => new Date(r.timestamp).toLocaleTimeString()),
        datasets: [
          {
            label: 'Latest Readings',
            data: data.map((r) => r.value),
            borderColor: 'rgba(75, 192, 192, 1)',
            tension: 0.1,
          },
        ],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
      },
    });
  }
}

<div class="card sensor-reading-card">
  <div class="card-title">
    <a routerLink="/sensor-readings">Sensor Readings</a>
  </div>
  <div class="card-content">
    <ng-container *ngIf="loading$ | async; else chartBlock">
      <p>Loading sensor readings...</p>
    </ng-container>
    <ng-template #chartBlock>
      <ng-container *ngIf="error$ | async as error">
        <p class="error">Error: {{ error?.message || error }}</p>
      </ng-container>
      <ng-container *ngIf="data$ | async as data">
        <canvas #readingsChart width="400" height="200"></canvas>
      </ng-container>
    </ng-template>
    <p>Total: {{ (data$ | async)?.length }}</p>
  </div>
</div>

// apps/mvvm-react/src/components/SensorReadingCard.tsx
import React, { useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import {
  Chart,
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import type { SensorReadingListData } from "@repo/view-models/SensorReadingViewModel";

// Register Chart.js components
Chart.register(
  LineController,
  LineElement,
  PointElement,
  LinearScale,
  CategoryScale,
  Title,
  Tooltip,
  Legend
);

interface SensorReadingCardProps {
  sensorReadings: SensorReadingListData;
}

const SensorReadingCard: React.FC<SensorReadingCardProps> = ({
  sensorReadings,
}) => {
  const chartInstanceRef = useRef<Chart | null>(null);

  useEffect(() => {
    if (sensorReadings.length === 0) {
      if (chartInstanceRef.current) {
        chartInstanceRef.current.destroy();
        chartInstanceRef.current = null;
      }
      return; // Don't render chart if there's no data
    }

    const canvasElement = document.getElementById(
      "sensorReadingsChart"
    ) as HTMLCanvasElement | null;
    if (!canvasElement) {
      console.error("Canvas element not found");
      return;
    }
    const ctx = canvasElement.getContext("2d");
    if (!ctx) {
      console.error("Failed to get canvas context");
      return;
    }

    // Destroy previous chart instance if it exists
    if (chartInstanceRef.current) {
      chartInstanceRef.current.destroy();
    }

    const chartData = {
      labels: sensorReadings.map((reading) =>
        new Date(reading.timestamp).toLocaleTimeString()
      ),
      datasets: [
        {
          label: "Sensor Value",
          data: sensorReadings.map((reading) => reading.value),
          fill: false,
          borderColor: "rgb(75, 192, 192)",
          tension: 0.1,
        },
      ],
    };

    const chartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        x: {
          title: {
            display: true,
            text: "Time",
          },
        },
        y: {
          title: {
            display: true,
            text: "Value",
          },
        },
      },
    };

    // Create new chart instance
    chartInstanceRef.current = new Chart(ctx, {
      type: "line",
      data: chartData,
      options: chartOptions,
    });

    // Cleanup function to destroy chart on component unmount
    return () => {
      if (chartInstanceRef.current) {
        chartInstanceRef.current.destroy();
        chartInstanceRef.current = null;
      }
    };
  }, [sensorReadings]); // Re-run effect if sensorReadings change

  return (
    <div className="card">
      <Link to="/sensor-readings" className="card-header-link">
        <h3 className="card-title">Sensor Readings</h3>
      </Link>
      <div className="card-content">
        <canvas id="sensorReadingsChart"></canvas>
      </div>
      <p className="card-content">Total Readings: {sensorReadings.length}</p>
    </div>
  );
};

export default SensorReadingCard;
