// apps/mvvm-vue/src/components/SensorCard.vue
<template>
  <div class="card">
    <router-link to="/sensors" class="card-header-link">
      <h3 class="card-title">Sensors</h3>
    </router-link>
    <p v-if="sensorListDataProp" class="card-content">
      Total: {{ sensorListDataProp.length }}
    </p>
    <p v-else class="card-content">Total: 0</p>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from "vue";
import type { SensorListData } from "@repo/view-models/SensorViewModel";
defineProps<{
  sensorListDataProp?: SensorListData | null;
}>();
</script>

<style scoped></style>

// apps/mvvm-react/src/components/SensorCard.tsx
import type { SensorListData } from "@repo/view-models/SensorViewModel";
import React from "react";
import { Link } from "react-router-dom";

interface SensorCardProps {
  sensors: SensorListData | null;
}

const SensorCard: React.FC<SensorCardProps> = ({ sensors }) => {
  if (!sensors) return null;
  return (
    <div className="card">
      <Link to="/sensors" className="card-header-link">
        <h3 className="card-title">Sensors</h3>
      </Link>
      <p className="card-content">Total: {sensors.length}</p>
    </div>
  );
};

export default SensorCard;
