// apps/mvvm-vue/src/components/GreenhouseList.vue
<template>
  <router-link to="/" class="back-button">
    <BackArrow class="back-arrow" />
  </router-link>
  <section class="flex-container flex-row">
    <form class="form-container" @submit.prevent="handleSubmit">
      <div class="form-group">
        <label for="name">Greenhouse Name:</label>
        <input
          type="text"
          id="name"
          name="name"
          v-model="formData.name"
          required
          class="input-field"
          placeholder="Enter greenhouse name"
        />
      </div>

      <div class="form-group">
        <label for="location">Location:</label>
        <textarea
          id="location"
          name="location"
          v-model="formData.location"
          required
          rows="3"
          class="textarea-field"
          placeholder="Location"
        ></textarea>
      </div>

      <div class="form-group">
        <label for="size">Size:</label>
        <select id="size" class="select-field" name="size" v-model="formData.size" required>
          <option value="">Select size</option>
          <option value="25sqm">25sqm / Small</option>
          <option value="50sqm">50sqm / Medium</option>
          <option value="100sqm">100sqm / Large</option>
        </select>
      </div>

      <div class="form-group">
        <label for="cropType">Crop Type:</label>
        <input
          type="text"
          name="cropType"
          id="cropType"
          v-model="formData.cropType"
          class="input-field"
          placeholder="Enter crop type"
        />
      </div>

      <button type="submit" class="button">Submit</button>
    </form>

    <div class="card" style="max-width: 600px">
      <h1 class="card-title">Greenhouses</h1>
      <div v-if="isLoading" class="card-content">
        <p>Loading greenhouses...</p>
      </div>
      <div v-else-if="greenhouses && greenhouses.length > 0">
        <ul class="card-content list">
          <li
            v-for="gh in greenhouses"
            :key="gh.id"
            class="list-item"
            style="font-size: 1.8rem; justify-content: space-between"
          >
            <span>{{ gh.name }}</span>
            <div class="button-group">
              <button class="button-tiny button-tiny-delete" @click="handleDelete(gh.id)">Delete</button>
              <button class="button-tiny button-tiny-edit" @click="handleUpdate(gh.id)">Edit</button>
            </div>
          </li>
        </ul>
      </div>
      <div v-else>
        <p class="card-content">No greenhouses found.</p>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted, ref, reactive } from 'vue';
import { greenHouseViewModel } from '@repo/view-models/GreenHouseViewModel';
import { useObservable } from '../hooks/useObservable';
// import BackArrow from '../assets/back-arrow.svg?component'; // Use ?component to import as a Vue component
import BackArrow from '../assets/back-arrow.svg';
// import type { GreenHouseModel } from '@repo/models/GreenHouseModel';

const isLoading = useObservable(greenHouseViewModel.isLoading$, true);
const greenhouses = useObservable(greenHouseViewModel.data$, []);

const greenHouseSizeOptions = ['25sqm', '50sqm', '100sqm'] as const;

const initialFormData = {
  name: '',
  location: '',
  size: '',
  cropType: '',
};
const formData = reactive({ ...initialFormData });
// To store the ID of the greenhouse being edited
const editingGreenhouseId = ref<string | null | undefined>(null);

onMounted(() => {
  greenHouseViewModel.fetchCommand.execute();
});

const handleSubmit = (event: Event) => {
  const form = event.target as HTMLFormElement;
  const nativeFormData = new FormData(form);
  const name = nativeFormData.get('name') as string;
  const location = nativeFormData.get('location') as string;
  const size = nativeFormData.get('size') as string;
  const cropType = nativeFormData.get('cropType') as string;

  const data = { name, location, size, cropType };

  if (editingGreenhouseId.value) {
    const existingGreenhouse = greenhouses.value?.find((gh) => gh.id === editingGreenhouseId.value);
    if (existingGreenhouse) {
      greenHouseViewModel.updateCommand.execute({
        id: existingGreenhouse.id || '',
        ...existingGreenhouse,
        // @ts-ignore - known issue with single object vs array
        name: data.name,
        location: data.location,
        size: data.size,
        cropType: data.cropType,
      });
    }
  } else {
    const existingGreenhouseByName = greenhouses.value?.find((gh) => gh.name === name);
    if (existingGreenhouseByName) {
      console.error('Greenhouse with this name already exists:', name);
      greenHouseViewModel.updateCommand.execute({
        id: existingGreenhouseByName.id || '',
        ...existingGreenhouseByName,
        // @ts-ignore - known issue with single object vs array
        name: data.name,
        location: data.location,
        size: data.size,
        cropType: data.cropType,
      });
      return;
    }
    // @ts-ignore - known issue with single object vs array
    greenHouseViewModel.createCommand.execute(data);
  }

  // Reset form and editing state
  Object.assign(formData, initialFormData);
  editingGreenhouseId.value = null;
  // Optionally, reset the native form if not using v-model for everything (though we are)
  form.reset();
};

const handleDelete = (id?: string) => {
  if (!id) {
    console.error('No ID provided for deletion');
    return;
  }
  greenHouseViewModel.deleteCommand.execute(id);
};

const handleUpdate = (id?: string) => {
  const greenhouse = greenhouses.value?.find((gh) => gh.id === id);
  if (!greenhouse) {
    console.error('Greenhouse not found for update:', id);
    return;
  }
  formData.name = greenhouse.name;
  formData.location = greenhouse.location;

  if (!greenHouseSizeOptions.includes(greenhouse.size as (typeof greenHouseSizeOptions)[number])) {
    console.error('Invalid greenhouse size:', greenhouse.size);
    formData.size = '100sqm'; // Default to '100sqm' if invalid
  } else {
    formData.size = greenhouse.size;
  }
  formData.cropType = greenhouse.cropType || '';
  editingGreenhouseId.value = greenhouse.id;
};
</script>
<style scoped></style>

// apps/mvvm-angular/src/app/components/greenhouse-list/greenhouse-list.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { greenHouseViewModel } from '@repo/view-models/GreenHouseViewModel';
import type { GreenHouseModel } from '@repo/models/GreenHouseModel';
import { BackIconComponent } from '../back-icon/back-icon.component';
import { Observable, Subscription, tap } from 'rxjs';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-greenhouse-list',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, BackIconComponent, RouterLink],
  templateUrl: './greenhouse-list.component.html',
  styleUrls: ['./greenhouse-list.component.scss'],
})
export class GreenhouseListComponent implements OnInit, OnDestroy {
  public vm = greenHouseViewModel;
  public greenhouses$: Observable<GreenHouseModel[] | null>;
  public loading$: Observable<boolean>;
  public error$: Observable<any>;

  greenhouseForm: FormGroup;
  editingGreenhouseId: string | null | undefined = null;
  greenhouses: GreenHouseModel[] = [];
  private greenhousesSubscription: Subscription | undefined;

  greenHouseSizeOptions = ['25sqm', '50sqm', '100sqm'] as const;

  constructor(private fb: FormBuilder) {
    this.greenhouseForm = this.fb.group({
      name: ['', Validators.required],
      location: ['', Validators.required],
      size: ['', Validators.required],
      cropType: [''],
    });

    this.greenhouses$ = this.vm.data$.pipe(
      tap(ghs => this.greenhouses = ghs || [])
    );
    this.loading$ = this.vm.isLoading$;
    this.error$ = this.vm.error$;
  }

  ngOnInit(): void {
    this.vm.fetchCommand.execute();
    this.greenhousesSubscription = this.greenhouses$.subscribe();

  }

  ngOnDestroy(): void {
    if (this.greenhousesSubscription) {
      this.greenhousesSubscription.unsubscribe();
    }
  }

  handleSubmit(): void {
    if (this.greenhouseForm.invalid) {
      console.error('Form is invalid');
      return;
    }

    const formDataValue = this.greenhouseForm.value;

    if (this.editingGreenhouseId) {
      const existingGreenhouse = this.greenhouses.find(gh => gh.id === this.editingGreenhouseId);
      if (existingGreenhouse) {
        this.vm.updateCommand.execute({
          id: this.editingGreenhouseId,
          ...existingGreenhouse, // spread existing to keep other properties
          name: formDataValue.name,
          location: formDataValue.location,
          size: formDataValue.size,
          cropType: formDataValue.cropType,
        });
      }
    } else {
      const existingGreenhouseByName = this.greenhouses.find(gh => gh.name === formDataValue.name);
      if (existingGreenhouseByName) {
        console.error('Greenhouse with this name already exists:', formDataValue.name);
        this.vm.updateCommand.execute({
          id: existingGreenhouseByName.id || '',
          ...existingGreenhouseByName,
          name: formDataValue.name,
          location: formDataValue.location,
          size: formDataValue.size,
          cropType: formDataValue.cropType,
        });
      } else {
        // @ts-ignore - known issue with single object vs array
        this.vm.createCommand.execute(formDataValue);
      }
    }

    this.greenhouseForm.reset();
    this.editingGreenhouseId = null;
  }

  handleUpdate(id?: string): void {
    if (!id) return;
    const greenhouse = this.greenhouses.find(gh => gh.id === id);
    if (greenhouse) {
      this.editingGreenhouseId = greenhouse.id;
      this.greenhouseForm.patchValue({
        name: greenhouse.name,
        location: greenhouse.location,
        size: greenhouse.size,
        cropType: greenhouse.cropType || '',
      });
    } else {
      console.error('Greenhouse not found for update:', id);
    }
  }

  handleDelete(id?: string): void {
    if (!id) {
      console.error('No ID provided for deletion');
      return;
    }
    this.vm.deleteCommand.execute(id);
    // If the deleted greenhouse was being edited, reset the form
    if (this.editingGreenhouseId === id) {
      this.greenhouseForm.reset();
      this.editingGreenhouseId = null;
    }
  }
}

<a routerLink="/" class="back-button">
  <back-icon></back-icon>
</a>
<section class="flex-container flex-row">
  <form [formGroup]="greenhouseForm" (ngSubmit)="handleSubmit()" class="form-container">
    <div class="form-group">
      <label for="name">Greenhouse Name:</label>
      <input
        type="text"
        id="name"
        formControlName="name"
        required
        class="input-field"
        placeholder="Enter greenhouse name"
      />
      <div *ngIf="greenhouseForm.get('name')?.invalid && (greenhouseForm.get('name')?.dirty || greenhouseForm.get('name')?.touched)" class="error-message">
        Name is required.
      </div>
    </div>

    <div class="form-group">
      <label for="location">Location:</label>
      <textarea
        id="location"
        formControlName="location"
        required
        rows="3"
        class="textarea-field"
        placeholder="Location"
      ></textarea>
      <div *ngIf="greenhouseForm.get('location')?.invalid && (greenhouseForm.get('location')?.dirty || greenhouseForm.get('location')?.touched)" class="error-message">
        Location is required.
      </div>
    </div>

    <div class="form-group">
      <label for="size">Size:</label>
      <select id="size" formControlName="size" class="select-field" required>
        <option value="">Select size</option>
        <option value="25sqm">25sqm / Small</option>
        <option value="50sqm">50sqm / Medium</option>
        <option value="100sqm">100sqm / Large</option>
      </select>
      <div *ngIf="greenhouseForm.get('size')?.invalid && (greenhouseForm.get('size')?.dirty || greenhouseForm.get('size')?.touched)" class="error-message">
        Size is required.
      </div>
    </div>

    <div class="form-group">
      <label for="cropType">Crop Type:</label>
      <input
        type="text"
        id="cropType"
        formControlName="cropType"
        class="input-field"
        placeholder="Enter crop type"
      />
    </div>

    <button type="submit" class="button" [disabled]="greenhouseForm.invalid">
      Submit
    </button>
  </form>

  <div class="card" style="max-width: 600px">
    <h1 class="card-title">Greenhouses</h1>
    <div *ngIf="loading$ | async" class="card-content">
      <p>Loading greenhouses...</p>
    </div>
    <ng-container *ngIf="greenhouses$ | async as greenhouseList">
      <div *ngIf="greenhouseList && greenhouseList.length > 0; else noGreenhouses" >
        <ul class="card-content list">
          <li *ngFor="let gh of greenhouseList" class="list-item" style="font-size: 1.8rem; justify-content: space-between">
            <span>{{ gh.name }}</span>
            <div class="button-group">
              <button
                class="button-tiny button-tiny-delete"
                (click)="handleDelete(gh.id)"
              >
                Delete
              </button>
              <button
                class="button-tiny button-tiny-edit"
                (click)="handleUpdate(gh.id)"
              >
                Edit
              </button>
            </div>
          </li>
        </ul>
      </div>
    </ng-container>
    <ng-template #noGreenhouses>
      <p *ngIf="!(loading$ | async)" class="card-content">No greenhouses found.</p>
    </ng-template>
  </div>
</section>
