// apps/mvvm-react/src/components/GreenhouseList.tsx
import { useEffect } from 'react';
import { greenHouseViewModel } from '@repo/view-models/GreenHouseViewModel';
import { useObservable } from '../hooks/useObservable';
import BackArrow from '../assets/back-arrow.svg';
import { Link } from 'react-router-dom';

export function GreenhouseList() {
  const greenHouses = useObservable(greenHouseViewModel.data$, []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        await greenHouseViewModel.fetchCommand.execute();
      } catch (error) {
        console.error('Error fetching greenhouses:', error);
      }
    };
    fetchData();
  }, []);

  return (
    <>
      <Link to="/" className="back-button">
        <img src={BackArrow} alt="Back to dashboard" className="back-arrow" />
      </Link>
      <div className="card">
        <h1 className="card-title">Greenhouses</h1>
        {greenHouses && greenHouses.length > 0 ? (
          <ul className="card-content list">
            {greenHouses.map((gh) => (
              <li key={gh.id} className="list-item">
                {gh.name} (ID: {gh.id})
              </li>
            ))}
          </ul>
        ) : (
          <p>No greenhouses found or still loading...</p>
        )}
      </div>
    </>
  );
}

// apps/mvvm-vue/src/components/GreenhouseList.vue
<template>
  <router-link to="/">
    <div class="back-arrow" aria-label="Back to Dashboard"><BackArrow /></div>
  </router-link>
  <div class="card">
    <h2 class="" card-title>Greenhouses</h2>
    <div v-if="isLoading" class="card-content">
      <p>Loading greenhouses...</p>
    </div>
    <div v-else-if="greenhouses && greenhouses.length > 0">
      <ul class="card-content list">
        <li v-for="gh in greenhouses" :key="gh.id" class="list-item">{{ gh.name }} (ID: {{ gh.id }})</li>
      </ul>
    </div>
    <div v-else>
      <p class="card-content">No greenhouses found.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';
import { greenHouseViewModel as importedGreenhouseVMInstance } from '@repo/view-models/GreenHouseViewModel';
import { useObservable } from '../hooks/useObservable';
import BackArrow from '../assets/back-arrow.svg';

const isLoading = useObservable(importedGreenhouseVMInstance.isLoading$, true);
const greenhouses = useObservable(importedGreenhouseVMInstance.data$, []);

onMounted(() => {
  importedGreenhouseVMInstance.fetchCommand.execute();
});
</script>

<style scoped></style>
