// apps/mvvm-react/src/components/GreenhouseCard.tsx
import type { GreenhouseListData } from "@repo/view-models/GreenHouseViewModel";
import React from "react";
import { Link } from "react-router-dom";

interface GreenhouseCardProps {
  greenHouses: GreenhouseListData | null;
}

const GreenhouseCard: React.FC<GreenhouseCardProps> = ({ greenHouses }) => {
  if (!greenHouses) return null;
  return (
    <div className="card">
      <Link to="/greenhouses" className="card-header-link">
        <h3 className="card-title">Greenhouses</h3>
      </Link>
      <p className="card-content">Total: {greenHouses.length}</p>
    </div>
  );
};

export default GreenhouseCard;

// apps/mvvm-vue/src/components/GreenhouseCard.vue
<template>
  <div class="card">
    <router-link to="/greenhouses" class="card-header-link">
      <h3 class="card-title">Greenhouses</h3>
    </router-link>
    <p v-if="greenhouseListDataProp" class="card-content">
      Total: {{ greenhouseListDataProp.length }}
    </p>
    <p v-else class="card-content">Total: 0</p>
  </div>
</template>

<script setup lang="ts">
import { defineProps } from "vue";
import type { GreenhouseListData } from "@repo/view-models/GreenHouseViewModel";

defineProps<{
  greenhouseListDataProp?: GreenhouseListData | null;
}>();
</script>

<style scoped></style>
