// apps/mvvm-react/src/components/SensorList.tsx
import { useEffect } from "react";
import { sensorViewModel } from "@repo/view-models/SensorViewModel";
import { useObservable } from "../hooks/useObservable";
import { Link } from "react-router-dom";
import BackArrow from "../assets/back-arrow.svg";

export function SensorList() {
  const sensors = useObservable(sensorViewModel.data$, []);

  useEffect(() => {
    const fetchData = async () => {
      await sensorViewModel.fetchCommand.execute();
    };
    fetchData();
  }, []);

  return (
    <>
      <Link to="/" className="back-button">
        <img
          src={BackArrow}
          alt="Back to dashboard"
          style={{ width: "36px", height: "36px" }}
        />
      </Link>
      <div className="card">
        <h1 className="card-title">Sensors</h1>
        {sensors && sensors.length > 0 ? (
          <ul className="card-content list">
            {sensors.map((sensor) => (
              <li key={sensor.id} className="list-item">
                {sensor.greenhouse.name} {sensor.type} (Status: {sensor.status})
              </li>
            ))}
          </ul>
        ) : (
          <p>No sensors found or still loading...</p>
        )}
      </div>
    </>
  );
}

// apps/mvvm-vue/src/components/SensorList.vue
<template>
  <router-link to="/">
    <div class="back-arrow" aria-label="Back to Dashboard"><BackArrow /></div>
  </router-link>
  <div class="card">
    <h4 class="card-title">
      Sensors {{ greenhouseId ? "for Greenhouse " + greenhouseId : "List" }}
    </h4>
    <div v-if="isLoading">
      <p class="content">Loading sensors...</p>
    </div>
    <div v-else-if="filteredSensors && filteredSensors.length > 0">
      <ul class="card-content list">
        <li
          v-for="sensor in filteredSensors"
          :key="sensor.id"
          class="list-item"
        >
          Sensor Type: {{ sensor.type }}
          <span v-if="sensor.greenhouse">
            | Greenhouse: {{ sensor.greenhouse.name }}</span
          >
          <span v-if="sensor.greenhouse.name">
            | Name: {{ sensor.greenhouse.name }}</span
          >
          (Status: {{ sensor.status || "N/A" }})
        </li>
      </ul>
    </div>
    <div v-else>
      <p>No sensors found {{ greenhouseId ? "for this greenhouse" : "" }}.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, defineProps, watch, computed } from "vue";
import { sensorViewModel as importedSensorVMInstance } from "@repo/view-models/SensorViewModel";
import { useObservable } from "../hooks/useObservable";
import BackArrow from "../assets/back-arrow.svg";

const props = defineProps<{
  greenhouseId?: string;
}>();

const isLoading = useObservable(importedSensorVMInstance.isLoading$, true);
const allSensors = useObservable(importedSensorVMInstance.data$, []);

const filteredSensors = computed(() => {
  if (!allSensors.value) return [];
  if (props.greenhouseId) {
    return allSensors.value.filter(
      (sensor: any) =>
        sensor.greenhouseId === props.greenhouseId ||
        (sensor.greenhouse && sensor.greenhouse.id === props.greenhouseId)
    );
  }
  return allSensors.value;
});

onMounted(() => {
  importedSensorVMInstance.fetchCommand.execute();
});

watch(
  () => props.greenhouseId,
  () => {}
);
</script>

<style scoped></style>
