// apps/mvvm-angular/src/app/components/sensor-list/sensor-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Replaced NgFor, NgClass
import {
  sensorViewModel,
  SensorListData,
} from '@repo/view-models/SensorViewModel';
import { Observable } from 'rxjs';
import { RouterLink } from '@angular/router';
import { BackIconComponent } from '../back-icon/back-icon.component';

@Component({
  selector: 'app-sensor-list',
  standalone: true,
  imports: [CommonModule, BackIconComponent, RouterLink],
  templateUrl: './sensor-list.component.html',
  styleUrl: './sensor-list.component.scss',
})
export class SensorListComponent {
  public vm = sensorViewModel;
  public data$: Observable<SensorListData | null>;
  public loading$: Observable<boolean>;
  public error$: Observable<any>;

  constructor() {
    this.data$ = this.vm.data$;
    this.loading$ = this.vm.isLoading$;
    this.error$ = this.vm.error$;

    this.vm.fetchCommand.execute();
  }

  // Keep getStatusClass or adapt if status is directly on sensor items
  // This depends on the structure of items in SensorListData
  getStatusClass(status: string | undefined): string {
    if (!status) return '';
    switch (status.toLowerCase()) {
      case 'online':
        return 'status-online';
      case 'offline':
        return 'status-offline';
      case 'error':
        return 'status-error';
      default:
        return '';
    }
  }
}

<a routerLink="/">
  <back-icon> </back-icon>
</a>
<div class="card">
  <h2 class="card-title">Sensor List</h2>
  <ul class="list" *ngIf="data$ | async as sensors">
    <li *ngFor="let sensor of sensors" class="list-item">
      <h3>{{ sensor.status }} ({{ sensor.id }})</h3>
      <p>Type:{{ sensor.type }}</p>
      <p>Greenhouse: {{ sensor.greenhouse.name }}</p>
      <p>
        Status:
        <span [ngClass]="getStatusClass(sensor.status)">{{
          sensor.status
        }}</span>
      </p>
    </li>
  </ul>
  <p *ngIf="loading$ | async">Loading.....</p>
</div>

// apps/mvvm-vue/src/components/SensorList.vue
<template>
  <router-link to="/">
    <div class="back-arrow" aria-label="Back to Dashboard"><BackArrow /></div>
  </router-link>
  <div class="card">
    <h4 class="card-title">
      Sensors {{ greenhouseId ? "for Greenhouse " + greenhouseId : "List" }}
    </h4>
    <div v-if="isLoading">
      <p class="content">Loading sensors...</p>
    </div>
    <div v-else-if="filteredSensors && filteredSensors.length > 0">
      <ul class="card-content list">
        <li
          v-for="sensor in filteredSensors"
          :key="sensor.id"
          class="list-item"
        >
          Sensor Type: {{ sensor.type }}
          <span v-if="sensor.greenhouse">
            | Greenhouse: {{ sensor.greenhouse.name }}</span
          >
          <span v-if="sensor.greenhouse.name">
            | Name: {{ sensor.greenhouse.name }}</span
          >
          (Status: {{ sensor.status || "N/A" }})
        </li>
      </ul>
    </div>
    <div v-else>
      <p>No sensors found {{ greenhouseId ? "for this greenhouse" : "" }}.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, defineProps, watch, computed } from "vue";
import { sensorViewModel as importedSensorVMInstance } from "@repo/view-models/SensorViewModel";
import { useObservable } from "../hooks/useObservable";
import BackArrow from "../assets/back-arrow.svg";

const props = defineProps<{
  greenhouseId?: string;
}>();

const isLoading = useObservable(importedSensorVMInstance.isLoading$, true);
const allSensors = useObservable(importedSensorVMInstance.data$, []);

const filteredSensors = computed(() => {
  if (!allSensors.value) return [];
  if (props.greenhouseId) {
    return allSensors.value.filter(
      (sensor: any) =>
        sensor.greenhouseId === props.greenhouseId ||
        (sensor.greenhouse && sensor.greenhouse.id === props.greenhouseId)
    );
  }
  return allSensors.value;
});

onMounted(() => {
  importedSensorVMInstance.fetchCommand.execute();
});

watch(
  () => props.greenhouseId,
  () => {}
);
</script>

<style scoped></style>
