// apps/mvvm-angular/src/app/components/threshold-alert-list/threshold-alert-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common'; // Includes NgFor, NgClass, DatePipe
import {
  thresholdAlertViewModel,
  ThresholdAlertListData,
} from '@repo/view-models/ThresholdAlertViewModel';
import { Observable } from 'rxjs';
import { RouterLink } from '@angular/router';
import { BackIconComponent } from '../back-icon/back-icon.component';

@Component({
  selector: 'app-threshold-alert-list',
  standalone: true,
  imports: [CommonModule, BackIconComponent, RouterLink],
  templateUrl: './threshold-alert-list.component.html',
  styleUrl: './threshold-alert-list.component.scss',
})
export class ThresholdAlertListComponent {
  public vm = thresholdAlertViewModel;
  public data$: Observable<ThresholdAlertListData | null>;
  public loading$: Observable<boolean>;
  public error$: Observable<any>;

  constructor() {
    this.data$ = this.vm.data$;
    this.loading$ = this.vm.isLoading$;
    this.error$ = this.vm.error$;

    this.vm.fetchCommand.execute();
  }

  getSeverityClass(severity: string | undefined): string {
    if (!severity) return '';
    switch (severity.toLowerCase()) {
      case 'critical':
        return 'severity-critical';
      case 'high':
        return 'severity-high';
      case 'medium':
        return 'severity-medium'; // Assuming 'medium' is a possible severity
      case 'low':
        return 'severity-low';
      default:
        return '';
    }
  }
}

<a routerLink="/">
  <back-icon> </back-icon>
</a>
<div class="card">
  <h2 class="card-title">Threshold Alert List</h2>

  <!-- Loading State -->
  <p class="card-content" *ngIf="loading$ | async">
    Loading threshold alerts...
  </p>

  <!-- Error State -->
  <p class="card-content" *ngIf="error$ | async as error" class="error">
    Error loading alerts: {{ error?.message || error }}
  </p>

  <!-- Data List -->
  <ul class="card-content list" *ngIf="data$ | async as alerts">
    <li *ngFor="let alert of alerts" class="list-item">
      <h3>Alert ID: {{ alert.id }}</h3>
      <p><strong>Sensor ID:</strong> {{ alert.greenhouseId }}</p>
      <p><strong>Type:</strong> {{ alert.sensorType }}</p>
    </li>
    <li *ngIf="alerts.length === 0">No threshold alerts to display.</li>
  </ul>
</div>

// apps/mvvm-vue/src/components/ThresholdAlertList.vue
<template>
  <router-link to="/">
    <div class="back-arrow" aria-label="Back to Dashboard"><BackArrow /></div>
  </router-link>
  <div class="card">
    <h3 class="card-title">Active Threshold Alerts</h3>
    <div v-if="isLoading">
      <p>Loading alerts...</p>
    </div>
    <ul
      v-else-if="alertsData && alertsData.length > 0"
      class="card-content list"
    >
      <li v-for="alert in alertsData" :key="alert.id" class="list-item">
        Alert ID: {{ alert.id }} | Sensor Type:
        {{ alert.sensorType || "N/A" }} | Threshold: Max
        {{ alert.maxValue ?? "N/A" }}, Min
        {{ alert.minValue ?? "N/A" }}
      </li>
    </ul>
    <div v-else>
      <p>No active threshold alerts.</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { thresholdAlertViewModel } from "@repo/view-models/ThresholdAlertViewModel";
import { useObservable } from "../hooks/useObservable";
import BackArrow from "../assets/back-arrow.svg";

const isLoading = useObservable(thresholdAlertViewModel.isLoading$, true);
const alertsData = useObservable(thresholdAlertViewModel.data$, []);

onMounted(() => {
  thresholdAlertViewModel.fetchCommand.execute();
});
</script>

<style scoped></style>
