// apps/mvvm-vue/src/layout/Header.vue
<template>
  <header class="header">
    <router-link to="/" class="header-item">Dashboard</router-link>
    <nav class="flex-container">
      <router-link to="/greenhouses" class="header-item"
        >Greenhouses</router-link
      >
      <router-link to="/sensors" class="header-item">Sensors</router-link>
      <router-link to="/sensor-readings" class="header-item"
        >Sensor Readings</router-link
      >
      <router-link to="/threshold-alerts" class="header-item"
        >Threshold Alerts</router-link
      >
    </nav>
  </header>
</template>

<script>
export default {
  name: "Header",
};
</script>
<style scoped>
a {
  font-weight: 500;
}
</style>

// apps/mvvm-react/src/layout/Header.tsx
import { Link } from 'react-router-dom';

export const Header = () => {
  return (
    <header className="header">
      <Link to="/" className="header-item">
        Dashboard
      </Link>
      <nav className="flex-container">
        <Link to="/greenhouses" className="header-item">
          Greenhouses
        </Link>
        <Link to="/sensors" className="header-item">
          Sensors
        </Link>
        <Link to="/sensor-readings" className="header-item">
          Sensor Readings
        </Link>
        <Link to="/threshold-alerts" className="header-item">
          Threshold Alerts
        </Link>
      </nav>
    </header>
  );
};
